#!/bin/bash
cd /var/www/meerkat_api/api_background
pip install -I --no-deps -e .

cd /var/www/meerkat_libs
pip install -I --no-deps -e .

cd /var/www/meerkat_abacus
rm database_is_setup
pip install -I --no-deps -e .

cd meerkat_abacus
celery -A task_queue worker -B -l info --concurrency 2
