#!/bin/bash
cd /var/www/meerkat_api/api_background
pip install -I --no-deps -e .

cd /var/www/meerkat_libs
pip install -I --no-deps -e .

cd /var/www/meerkat_libs
pip install -e . 

cd /var/www/meerkat_abacus
pip install -r requirements.txt
rm database_is_setup
pip install -I --no-deps -e .

cd /var/www/meerkat_runner

celery -A  meerkat_runner.celery.app worker -l info --concurrency 2
